Repository Techie006/FE, pull requests merged in 2022-10, with the labels that each got.

#43 CookingClass 화면 1차 완성
  .vscode/settings.json
  src/components/class/ChatFrame.jsx
  src/components/class/Code.jsx
  src/components/class/VideoFrame.jsx
  src/components/class/sock-js/Chat.jsx
  src/components/class/sock-js/ChatHeader.jsx
  src/components/class/sock-js/Chats.jsx
  src/components/class/sock-js/CreateChat.jsx
  src/components/class/sock-js/Notice.jsx
  src/components/class/video/ClassVideo.jsx
  src/components/class/video/OpenViduVideo.jsx
  src/components/class/video/VideoHeader.jsx
  src/components/classes/ClassesFrame.jsx
  src/components/classes/modal/CreateModal.jsx
  src/elements/atoms/Button.jsx
  src/elements/molecules/Ingredients.jsx
  src/modules/redux/cookingClass.jsx
Labels: enhancement

#46 Final
  README.md
  src/modules/store/ConfigStore.jsx
Labels: deploy

#47 feat: update bookmark recipe, add recipe search
  package.json
  src/components/auth/GoogleLogin.jsx
  src/components/auth/KakaoLogin.jsx
  src/components/auth/SigninForm.jsx
  src/components/recipes/BookMarkedRecipes.jsx
  src/components/recipes/Recipe.jsx
  src/components/recipes/Recipes.jsx
  src/modules/store/ConfigStore.jsx
  yarn.lock
Labels: feature

#48 feat: add recipe search page
  src/components/auth/SigninForm.jsx
  src/components/recipes/BookMarkedRecipes.jsx
  src/components/recipes/DetailModal.jsx
  src/components/recipes/DoneModal.jsx
  src/components/recipes/Recipe.jsx
  src/components/recipes/Recipes.jsx
  src/elements/atoms/Link.jsx
Labels: feature

#52 feat: update recipe page
  src/components/auth/SigninForm.jsx
  src/components/common/Header.jsx
  src/components/recipes/BookMarkedRecipes.jsx
  src/components/recipes/Recipe.jsx
  src/components/recipes/RecipesLayout.jsx
  src/pages/Recipe.jsx
Labels: feature

#53 feat: update auth page
  src/components/auth/SigninForm.jsx
  src/components/home/HomeIngredients.jsx
Labels: feature

#54 feat: recipe페이지 디테일 모달 작업완료
  src/components/auth/SigninForm.jsx
  src/components/recipes/BookMarkedRecipes.jsx
  src/components/recipes/DetailModal.jsx
  src/components/recipes/DoneModal.jsx
  src/components/recipes/Recipe.jsx
  src/components/recipes/Recipes.jsx
Labels: feature

#61 세부 기능 조정
  .env
  src/components/auth/OAuth/OAuth.jsx
  src/components/auth/SignIn.jsx
  src/components/auth/SignUp.jsx
  src/components/class/video/OpenViduVideo.jsx
Labels: bug

#63 feat: 메인페이지 통계 추가
  src/components/home/HomeLayout.jsx
  src/components/statistics/Daily.jsx
Labels: feature

#64 feat: update onclick button
  src/components/modals/CreateIngredientModal.jsx
  src/components/modals/UpdateProfileModal.jsx
Labels: feature

#65 Recipes
  src/components/home/RecommendRecipes.jsx
  src/components/recipes/RecipesFrame.jsx
  src/components/recipes/RecipesHeader.jsx
  src/pages/Recipes.jsx
  src/routers/Routers.jsx
Labels: refactoring
